# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494fcd9c7f6be73f403cdcee9e2ef38c63cd72ff14fa047641f47556f0b2f7a8449b5d98d64752fd0ccff36b4f72cefa6522e5f1dab91244c08e3fcf35b8fe79

test:
  secret_key_base: 6335f5f075f5e2e5c3a20caa225fa6c915377be711f33e071ddd39f785f32fcd3650337cfc58a609168b2868486b4c5f2fbca1cd3dc7dffac58aed42474add44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
